# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f3c64e0d1424407ed00200c49f684fc76bc7272fef72c615dfa397fbb8b61c609744c60f4cdd1ffa55809c5708897e84cf8507e047081143277064b795678aa

test:
  secret_key_base: 2f05e9c2eb9049c01ec1cdc0ccc807dead0d7935a3e8f3f54e58ec8a43b67b6284a18a2e8584fa49998f846030096648822947fe05720cd6b86b3e2f6a59e0e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
